In [1]:
!pip install numpy

In [27]:
import numpy as np
a = np.array([8, 9, 5])
print(a)
print(a.ndim)

[8 9 5]
1


In [26]:
b = np.array([(2.3,4,6),(3,6,7)])
print(b)
print(b.ndim)

[[2.3 4.  6. ]
 [3.  6.  7. ]]
2


In [25]:
c = np.array([[(2,5,6),(6,7,8)],[(8,9,4),(6,8,3)]])
print(c)
print(c.ndim)

[[[2 5 6]
  [6 7 8]]

 [[8 9 4]
  [6 8 3]]]
3


In [28]:
d = np.array(["hello"])
print(d)
print(d.ndim)

['hello']
1


In [29]:
e = np.array([("h","e","l","l","o"),("w","o","r","l","d")])
print(e)
print(e.ndim)

[['h' 'e' 'l' 'l' 'o']
 ['w' 'o' 'r' 'l' 'd']]
2


In [34]:
f = np.array(["hello","world"])
print(f)
print(f.ndim)

['hello' 'world']
1


In [44]:
#place holders
a = np.zeros((4,2)) #(rows,colums)
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [47]:
b = np.ones((2,3,2)) #(shape,rows,colums)
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [48]:
c = np.arange(2,30,2)#(startvalue,endvalue,steps)(steps n-1,3-2=1)
print(c)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [52]:
d = np.arange(2.5,14.5,2.5)
print(d)

[ 2.5  5.   7.5 10.  12.5]


In [51]:
a = np.linspace(1,14,10) #(startvalue,endvalue,any no of samples)
print(a)

[ 1.          2.44444444  3.88888889  5.33333333  6.77777778  8.22222222
  9.66666667 11.11111111 12.55555556 14.        ]


In [57]:
#constant values
a = np.full((10),10)
print(a)
print(a.ndim)

[10 10 10 10 10 10 10 10 10 10]
1


In [60]:
b = np.full((2,5),5)
print(b)
print(b.ndim)

[[5 5 5 5 5]
 [5 5 5 5 5]]
2


In [61]:
c = np.full((2,5,6),5)
print(c)
print(c.ndim)

[[[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]

 [[5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]
  [5 5 5 5 5 5]]]
3


In [63]:
#create a 2*2 identity matrix
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [66]:
b = np.eye(5)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [73]:
#create an array with random value
a = np.random.random((3,9))
print(a)

[[0.10665488 0.74981117 0.54883855 0.81682947 0.48581999 0.47299423
  0.72662886 0.47651003 0.47835322]
 [0.51048434 0.53664929 0.23427393 0.71031011 0.92393337 0.71111853
  0.40871253 0.72920838 0.62375713]
 [0.6662356  0.32228545 0.2110939  0.91498525 0.04831908 0.97392594
  0.55461988 0.23591282 0.63577335]]


In [78]:
b = np.random.randint((6,15))
print(b)

[4 9]


In [79]:
#to find shape of an array
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [81]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [99]:
arr = np.array([["h",2,"e",4],["w",6,"u",8]])
print(arr.shape)

(2, 4)


In [100]:
arr = np.array([[[1,"e",3],
                 [4,"i",6],
                [7,"o",9],
                [5,"t",7]]])
print(arr.shape)
print(arr.ndim)

(1, 4, 3)
3


In [97]:
#to find no of elements in array
a = np.array([[1,2,3,4],
             [5,6,7,8]
              ])
print(a.size)

8


In [98]:
b = np.array([["h","e","l","l","o"],
            ["w","o","r","l","d"]])
print(b.size)

10


In [113]:
#to find len of array
i = np.array(["m","e","g","h"])
print(len(i))

4


In [115]:
g = np.array([(5,6,7),
               (1,2,3)])
print(len(g))
print(g.ndim)

2
2


In [120]:
h = np.array([[(1,2,3),
              (4,5,6)],
              [(6,3,7),
              (5,9,8)]])
print(h.ndim)
print(len(h))

3
2
